packages:
  - ./
  - playground

catalog:
  '@antfu/eslint-config': ^4.17.0
  '@nuxt/devtools': ^2.6.2
  '@nuxt/eslint-config': ^1.6.0
  '@nuxt/kit': ^3.17.7
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^3.17.7
  '@nuxt/test-utils': ^3.19.2
  '@nuxt/ui': ^3.2.0
  '@types/node': ^24.0.15
  '@unocss/eslint-plugin': ^66.3.3
  '@vueuse/core': ^13.5.0
  ansis: ^4.1.0
  changelogen: ^0.6.2
  chokidar: ^4.0.3
  defu: ^6.1.4
  discord.js: ^14.21.0
  eslint: ^9.31.0
  knitwork: ^1.2.0
  lint-staged: ^16.1.2
  listhen: ^1.9.0
  nuxt: ^3.17.7
  rollup: ^4.45.1
  simple-git-hooks: ^2.13.0
  simple-icons: ^15.6.0
  typescript: ~5.8.3
  unbuild: ^3.5.0
  unocss: ^66.3.3
  vitest: ^3.2.4
  vue-tsc: ^2.2.12
  ws: ^8.18.3

onlyBuiltDependencies:
  - simple-git-hooks
