packages:
  - ./
  - playground

catalog:
  '@antfu/eslint-config': ^4.16.1
  '@nuxt/devtools': ^2.5.0
  '@nuxt/eslint-config': ^1.4.1
  '@nuxt/kit': ^3.17.5
  '@nuxt/module-builder': ^1.0.1
  '@nuxt/schema': ^3.17.5
  '@nuxt/test-utils': ^3.19.1
  '@nuxt/ui': ^3.2.0
  '@types/node': ^24.0.4
  '@unocss/eslint-plugin': ^66.3.2
  '@vueuse/core': ^13.4.0
  ansis: ^4.1.0
  changelogen: ^0.6.1
  defu: ^6.1.4
  discord.js: ^14.21.0
  eslint: ^9.29.0
  knitwork: ^1.2.0
  lint-staged: ^16.1.2
  listhen: ^1.9.0
  nuxt: ^3.17.5
  simple-git-hooks: ^2.13.0
  simple-icons: ^15.3.0
  typescript: ~5.8.3
  unbuild: ^3.5.0
  unocss: ^66.3.2
  vitest: ^3.2.4
  vue-tsc: ^2.2.10
  ws: ^8.18.2

onlyBuiltDependencies:
  - simple-git-hooks
