name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          SKIP_INSTALL_SIMPLE_GIT_HOOKS: 1
      - name: Lint
        run: bun run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          SKIP_INSTALL_SIMPLE_GIT_HOOKS: 1
      - name: Playground prepare
        run: bun run dev:prepare
      - name: Test
        run: bun run test
      - name: Type check
        run: bunx tsc --noEmit --project tsconfig.json
